name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Set environment variables
        run: echo "VITE_EMAILJS_USERID=${{ secrets.VITE_EMAILJS_USERID }}" >> $GITHUB_ENV
        # Add additional environment variables here if needed
      - name: Set more environment variables (optional)
        run: echo "VITE_EMAILJS_TEMPLATEID=${{ secrets.VITE_EMAILJS_TEMPLATEID }}" >> $GITHUB_ENV
      - name: Set more environment variables (optional)
        run: echo "VITE_EMAILJS_RECEIVERID=${{ secrets.VITE_EMAILJS_RECEIVERID }}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
